import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import React from 'react'

const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>
export default function RootLayout ({
  children
}: RootLayoutProps): React.JSX.Element {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  )
}
